SET search_path TO mimiciv;


DROP TABLE IF EXISTS EDSTAYS CASCADE;
CREATE TABLE EDSTAYS
(
	SUBJECT_ID INT NOT NULL,
	HADM_ID INT,
	STAY_ID INT NOT NULL,
	INTIME TIMESTAMP(0) NOT NULL,
	OUTTIME TIMESTAMP(0) NOT NULL
);

DROP TABLE IF EXISTS DIAGNOSIS CASCADE;
CREATE TABLE DIAGNOSIS
(
	SUBJECT_ID INT NOT NULL,
	STAY_ID INT NOT NULL,
	SEQ_NUM INT NOT NULL,
	ICD_CODE VARCHAR(7) NOT NULL,
	ICD_VERSION INT NOT NULL,
	ICD_TITLE VARCHAR(160) NOT NULL

);

DROP TABLE IF EXISTS MEDRECON CASCADE;
CREATE TABLE MEDRECON
(
	SUBJECT_ID INT NOT NULL,
	STAY_ID INT NOT NULL,
	CHARTTIME TIMESTAMP(0) NOT NULL,
	NAME VARCHAR(140) NOT NULL,
	GSN INT NOT NULL,
	NDC VARCHAR(11) NOT NULL,
	ETC_RN INT NOT NULL,
	ETCCODE INT,
	ETCDESCRIPTION VARCHAR(80) 

);

DROP TABLE IF EXISTS PYXIS CASCADE;
CREATE TABLE PYXIS
(
	SUBJECT_ID INT NOT NULL,
	STAY_ID INT NOT NULL,
	CHARTTIME TIMESTAMP(0) NOT NULL,
	MED_RN INT NOT NULL,
	NAME VARCHAR(60) NOT NULL,
	GSN_RN INT NOT NULL,
	GSN INT 
);

DROP TABLE IF EXISTS TRIAGE CASCADE;
CREATE TABLE TRIAGE
(
	SUBJECT_ID INT NOT NULL,
	STAY_ID INT NOT NULL,
	TEMPERATURE DOUBLE PRECISION,
	HEARTRATE DOUBLE PRECISION,
	RESPRATE DOUBLE PRECISION,
	O2SAT DOUBLE PRECISION,
	SBP DOUBLE PRECISION,
	DBP DOUBLE PRECISION,
	PAIN DOUBLE PRECISION,
	ACUITY DOUBLE PRECISION,
	CHIEFCOMPLAINT VARCHAR(150)
);

DROP TABLE IF EXISTS VITALSIGN CASCADE;
CREATE TABLE VITALSIGN
(
	SUBJECT_ID INT NOT NULL,
	STAY_ID INT NOT NULL,
	CHARTTIME TIMESTAMP(0) NOT NULL,
	TEMPERATURE DOUBLE PRECISION,
	HEARTRATE DOUBLE PRECISION,
	RESPRATE DOUBLE PRECISION,
	O2SAT DOUBLE PRECISION,
	SBP DOUBLE PRECISION,
	DBP DOUBLE PRECISION,
	RHYTHM VARCHAR(80),
	PAIN VARCHAR(410) 
);

